# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name:  Doris CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install dependency
        run: sudo apt-get install g++ ant cmake zip byacc flex automake libtool binutils-dev libiberty-dev bison python2.7 libncurses5-dev lsb-release mlocate
      
      - name: checkout source code
        uses: actions/checkout@v2
        
      - name: build thirdparty
        run: |
              export REPOSITORY_URL=https://doris-incubating-repo.bj.bcebos.com/thirdparty
              export DORIS_HOME=$TRAVIS_BUILD_DIR
              cd $GITHUB_WORKSPACE/
              bash env.sh
              bash thirdparty/concurrent-build-thirdparty.sh
              
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: build fe
        run: |
          cd $GITHUB_WORKSPACE
          bash build.sh --be
        
      - name: fe ut
        run: |
          cd $GITHUB_WORKSPACE
          bash run-ut.sh
